# Site settings
email: tougao@kehuanshuangyue.com
baseurl: "https://sfbm.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: 科幻双月杂志
description: 
url: ""
twitter_username: 
default_img: "http://sfbm.sinaapp.com/favicon.ico"

# Profile settings
name: Hubert Wang
profile_img: 
profile: 
social:


# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
